### ISSUE TITLE
It doesn't work(on my LinuxMint distro).

### ISSUE THREAD

**Issue by cydside** [quicktype/quicktype-vscode#7] opened 2018-03-19 11:34 UTC
System:
> 4.13.0-37-generic GNU/Linux
> Distributor ID: LinuxMint
> Release:        18.3
> Codename:       sylvia

VSCODE:

> Version 1.21.1
> Commit 79b44aa704ce542d8ca4a3cc44cfca566e7720f1
> Data 2018-03-14T14:46:30.761Z
> Shell 1.7.9
> Renderer 58.0.3029.110
> Nodo 7.9.0
>  x64

Installed and removed more times, nothing to do, it doesn't work!

**Comment by schani** [comment] 2018-06-18 14:33
@cydside Could you please try again with the latest version (>=11.0.6)?

**Comment by schani** [comment] 2018-06-19 01:04
I can confirm this running on Ubuntu 18.04.

**Comment by cydside** [comment] 2018-06-19 07:52
I'm sorry for the late. Updated to 11.0.6, VSCode Version 1.24.1 and it's not working.

**Comment by schani** [comment] 2018-06-19 14:16
Yes.  I just discovered my last comment was ambiguous.  I can confirm the bug ;-)

**Comment by cydside** [comment] 2018-06-19 17:38
Thanks for your effort, it's a really useful software. I'm using the online version in the meantime.

**Comment by schani** [comment] 2018-06-19 19:04
This seems to be a clipboard issue.  I'm on it.

**Comment by schani** [comment] 2018-06-19 19:53
Fixed in #9

**Closed by schani** 2018-06-19 19:53 UTC
Labels: bug
